# Generated by Django 4.2.23 on 2025-07-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='visit_date',
            field=models.DateTimeField(),
        ),
    ]
