# Generated by Django 4.2.23 on 2025-07-16 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dentalclinic', '0002_alter_visithistory_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
