# Generated by Django 5.2.4 on 2025-07-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalclinic', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='op_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
