# Generated by Django 5.2.4 on 2025-07-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalclinic', '0003_patient_op_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='op_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
