# Generated by Django 5.2.4 on 2025-07-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalclinic', '0004_alter_patient_op_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='op_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
