# Generated by Django 4.2.23 on 2025-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalclinic', '0006_visithistory_xray_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.FloatField(),
        ),
    ]
