# Generated by Django 5.2.4 on 2025-07-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalclinic', '0006_visithistory_xray_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.FloatField(),
        ),
    ]
